config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :articles
  devise_for :users
  resources :contacts
  resources :events
  root to: "home#index"
  get '/privacy_policy', to: 'home#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :contacts
      resources :articles
      resources :events
      resources :links
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/api/v1/articles_controller.rb
module Api
      module V1
    class ArticlesController < ActionController::API
      before_action :set_article, only: [:show, :update, :destroy]
      before_action :authenticate_token


      # GET /articles
      def index
        if @is_authenticated
          @article = Article.where("created_at >= ?", 90.days.ago).order(publishedAt: :desc)

          render json: @article
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # GET /articles/1
      def show
        if @is_authenticated
          render json: @article
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # POST /articles
      def create
        if @is_authenticated
          @article = Article.new(article_params)

          if @article.save
            render json: @article, status: :created, location: @article
          else
            render json: @article.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # PATCH/PUT /articles/1
      def update
        if @is_authenticated
          if @article.update(article_params)
            render json: @article
          else
            render json: @article.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # DELETE /articles/1
      def destroy
        if @is_authenticated
          @article.destroy
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      private
        #This is to authenticate that the call is set from an account of the front-end
        def authenticate_token
          @is_authenticated = false
          if request.headers["TOKEN"]
            if request.headers["TOKEN"] == "AppDipre"
              @is_authenticated = true
            end
          end
        end
        # Use callbacks to share common setup or constraints between actions.
        def set_article
          @article = Article.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def article_params
          params.require(:article).permit(:title, :description, :publishedAt, :source, :urlToImage, :url)
        end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :publishedAt, :source, :urlToImage, :url)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">
    <%= form_with(model: article, local: true, class: "contact100-form validate-form") do |form| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <span class="contact100-form-title">
        Crea una nueva noticia
      </span>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :title, class: "input100", placeholder: "Titular" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_area :description, class: "input100", placeholder: "Descripción" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <label for="article_publishedAt" class="datelabel" >Publicada en:</label>
        <%= form.date_select :publishedAt, class: "input100", placeholder: "Publicada en" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :source, class: "input100", placeholder: "Fuente" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :urlToImage, class: "input100", placeholder: "Url a la imagen" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :url, class: "input100", placeholder: "Url" %>
        <span class="focus-input100"></span>
      </div>

      <div class="container-contact100-form-btn">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_form1.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">
    <%= form_with(model: article, local: true, class: "contact100-form validate-form") do |form| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <span class="contact100-form-title">
        Editando noticia
      </span>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :title, class: "input100", placeholder: "Título" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_area :description, class: "input100", placeholder: "Descripción" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <label for="article_publishedAt">Publicada en:</label>
        <%= form.date_select :publishedAt, class: "input100", placeholder: "Publicada en" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :source, class: "input100", placeholder: "Fuente" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :urlToImage, class: "input100", placeholder: "Url a la imagen" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :url, class: "input100", placeholder: "Url" %>
        <span class="focus-input100"></span>
      </div>

      <div class="container-contact100-form-btn">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form1', article: @article %>

<%= link_to 'Ver noticia', @article %> |
<%= link_to 'Atrás', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticias</h1>


<div class="jss12 jss16 jss13">
  <table class="jss320 table">
    <thead class="jss321">
      <tr class="jss322 jss325">
        <th class="jss327 jss328" scope="col">Título</th>
        <th class="jss327 jss328 center" scope="col">Publicada en</th>
        <th class="jss327 jss328 center" scope="col">Fuente</th>
        <th class="jss327 jss328 center" scope="col">Url</th>
        <th class="jss327 jss328 center" scope="col">Url a la imagen</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody class="jss348">
      <% @articles.each do |article| %>
        <tr class="jss322">
          <td class="jss327 jss329" style="width: 10%;"><%= article.title %></td>
          <td class="jss327 jss329 center"><%= article.publishedAt %></td>
          <td class="jss327 jss329"><%= article.source %></td>
          <td class="jss327 jss329"><%= article.url %></td>
          <td class="jss327 jss329"><%= article.urlToImage %></td>
          <td class="jss327 jss329 center"><%= link_to 'Ver más', article %></td>
          <td class="jss327 jss329 center"><%= link_to 'Editar', edit_article_path(article) %></td>
          <td class="jss327 jss329 center"><%= link_to 'Eliminar', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<form method="get" action="/articles/new" class="button_to">
  <button tabindex="0" class="jss91 jss359 jss368 jss369 jss371 jss372" type="submit">
    <span class="jss360">
      <svg class="jss346 jss424" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M19 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-2 10h-4v4h-2v-4H7v-2h4V7h2v4h4v2z"></path></g>
      </svg>
      Nueva noticia
    </span>
    <span class="jss94">
    </span>
  </button>
</form

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

<%= link_to 'Atrás', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Cuerpo de la noticia:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Publicada en:</strong>
  <%= @article.publishedAt %>
</p>

<p>
  <strong>Fuente:</strong>
  <%= @article.source %>
</p>

<p>
  <strong>Url a la imagen:</strong>
  <%= @article.urlToImage %>
</p>

<p>
  <strong>Url:</strong>
  <%= @article.url %>
</p>

<%= link_to 'Editar', edit_article_path(@article) %> |
<%= link_to 'Atrás', articles_path %>