config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :articles
  devise_for :users
  resources :contacts
  resources :events
  root to: "home#index"
  get '/privacy_policy', to: 'home#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :contacts
      resources :articles
      resources :events
      resources :links
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ActionController::API
      before_action :set_event, only: [:show, :update, :destroy]
      before_action :authenticate_token

      # GET /events
      def index
        if @is_authenticated
          @events = Event.where("to_date >= ?", DateTime.now).order(date: :desc)
          render json: @events
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # GET /events/1
      def show
        if @is_authenticated
          render json: @event
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end

      end

      # POST /events
      def create
        if @is_authenticated
          @event = Event.new(event_params)

          if @event.save
            render json: @event, status: :created, location: @event
          else
            render json: @event.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # PATCH/PUT /events/1
      def update
        if @is_authenticated
          if @event.update(event_params)
            render json: @event
          else
            render json: @event.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # DELETE /events/1
      def destroy
        if @is_authenticated
          @event.destroy
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      private
        #This is to authenticate that the call is set from an account of the front-end
        def authenticate_token
          @is_authenticated = false
          if request.headers["TOKEN"]
            if request.headers["TOKEN"] == "AppDipre"
              @is_authenticated = true
            end
          end
        end
        # Use callbacks to share common setup or constraints between actions.
        def set_event
          @event = Event.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def event_params
          params.require(:event).permit(:title, :description, :epigraph, :date, :to_date, :hour, :url)
        end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :date, :epigraph, :to_date, :url, :hour)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">
    <%= form_with(model: event, local: true, class: "contact100-form validate-form") do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <span class="contact100-form-title">
        Crea un nuevo evento
      </span>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :title, class: "input100", placeholder: "Título" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_area :description, class: "input100", placeholder: "Descripción" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <label for="event_date" class="datelabel" >Fecha:</label>
        <%= form.date_select :date, class: "input100", placeholder: "Fecha" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :epigraph, class: "input100", placeholder: "Epígrafe" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <label for="event_date" class="datelabel" >Fecha de fin:</label>
        <%= form.date_select :to_date, class: "input100", placeholder: "Fecha" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :url, class: "input100", placeholder: "Url" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :hour, class: "input100", placeholder: "Hora del evento" %>
        <span class="focus-input100"></span>
      </div>

      <div class="container-contact100-form-btn">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_form0.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">
    <%= form_with(model: event, local: true, class: "contact100-form validate-form") do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <span class="contact100-form-title">
        Editando un evento
      </span>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :title, class: "input100", placeholder: "Título" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_area :description, class: "input100", placeholder: "Descripción" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <label for="event_date" class="datelabel" >Fecha:</label>
        <%= form.date_select :date, class: "input100", placeholder: "Fecha" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :epigraph, class: "input100", placeholder: "Epígrafe" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <label for="event_date" class="datelabel" >Fecha de fin:</label>
        <%= form.date_select :to_date, class: "input100", placeholder: "Fecha" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :url, class: "input100", placeholder: "Url" %>
        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input">
        <%= form.text_field :hour, class: "input100", placeholder: "Hora del evento" %>
        <span class="focus-input100"></span>
      </div>

      <div class="container-contact100-form-btn">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'form0', event: @event %>

<%= link_to 'Mostrar evento', @event %> |
<%= link_to 'Atrás', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<div class="jss12 jss16 jss13">
  <table class="jss320 table">
    <thead class="jss321">
      <tr class="jss322 jss325">
        <th class="jss327 jss328" scope="col">Título</th>
        <th class="jss327 jss328" scope="col"><span tabindex="0" class="jss91 jss901 jss902" role="button">Descripción</span></th>
        <th class="jss327 jss328 center" scope="col">Epígrafe</th>
        <th class="jss327 jss328 center" scope="col">Fecha inicio</th>
        <th class="jss327 jss328 center" scope="col">Fecha de fin</th>
        <th class="jss327 jss328 center" scope="col">Hora</th>
        <th class="jss327 jss328 center" scope="col">Url</th>
      </tr>
    </thead>
    <tbody class="jss348">
      <% @events.each do |event| %>
        <tr class="jss322">
          <td class="jss327 jss329" style="width: 10%;"><%= event.title %></td>
          <td class="jss327 jss329" style="width: 20%;"><%= event.description[0..100] << "..." %></td>
          <td class="jss327 jss329 center"><%= event.epigraph %></td>
          <td class="jss327 jss329 center"><%= event.date %></td>
          <td class="jss327 jss329 center"><%= event.to_date %></td>
          <td class="jss327 jss329 center"><%= event.hour %></td>
          <td class="jss327 jss329 center"><%= event.url %></td>
          <td class="jss327 jss329 center"><%= link_to 'Ver más', event %></td>
          <td class="jss327 jss329 center"><%= link_to 'Editar', edit_event_path(event) %></td>
          <td class="jss327 jss329 center"><%= link_to 'Eliminar', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<form method="get" action="/events/new" class="button_to">
  <button tabindex="0" class="jss91 jss359 jss368 jss369 jss371 jss372" type="submit">
    <span class="jss360">
      <svg class="jss346 jss424" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M19 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-2 10h-4v4h-2v-4H7v-2h4V7h2v4h4v2z"></path></g>
      </svg>
      Nuevo evento
    </span>
    <span class="jss94">
    </span>
  </button>
</form>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%= link_to 'Atrás', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Epígrafe:</strong>
  <%= @event.epigraph %>
</p>

<p>
  <strong>Fecha de fin:</strong>
  <%= @event.to_date %>
</p>

<p>
  <strong>Url:</strong>
  <%= @event.url %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @event.hour %>
</p>

<%= link_to 'Editar', edit_event_path(@event) %> |
<%= link_to 'Atrás', events_path %>