config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :articles
  devise_for :users
  resources :contacts
  resources :events
  root to: "home#index"
  get '/privacy_policy', to: 'home#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :contacts
      resources :articles
      resources :events
      resources :links
    end
  end
end

app/models/link.rb
class Link < ApplicationRecord
end

app/controllers/api/v1/links_controller.rb
module Api
  module V1
    class LinksController < ActionController::API
      before_action :set_link, only: [:show, :update, :destroy]
      before_action :authenticate_token


      # GET /links
      def index
        if @is_authenticated
          @link = Link.all

          render json: @link
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # GET /links/1
      def show
        if @is_authenticated
          render json: @link
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # POST /links
      def create
        if @is_authenticated
          @link = Link.new(link_params)

          if @link.save
            render json: @link, status: :created, location: @link
          else
            render json: @link.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # PATCH/PUT /links/1
      def update
        if @is_authenticated
          if @link.update(link_params)
            render json: @link
          else
            render json: @link.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # DELETE /links/1
      def destroy
        if @is_authenticated
          @link.destroy
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      private
        #This is to authenticate that the call is set from an account of the front-end
        def authenticate_token
          @is_authenticated = false
          if request.headers["TOKEN"]
            if request.headers["TOKEN"] == "AppDipre"
              @is_authenticated = true
            end
          end
        end
        # Use callbacks to share common setup or constraints between actions.
        def set_link
          @link = Link.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def link_params
          params.require(:link).permit(:title, :description, :url)
        end
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :description)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.url %></td>
        <td><%= link.description %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @link.description %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>