config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :articles
  devise_for :users
  resources :contacts
  resources :events
  root to: "home#index"
  get '/privacy_policy', to: 'home#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :contacts
      resources :articles
      resources :events
      resources :links
    end
  end
end

app/views/layouts/_navbar.html.erb
<ul class="ul2">
  <% if user_signed_in? %>
    <li><%=link_to "Home", root_path, :class=>"active" %></li>
    <li><%=link_to "Eventos", events_path %></li>
    <li><%=link_to "Noticias", articles_path %></li>
    <li><%=link_to'Contactos', contacts_path %></li>
    <li><%=link_to'Links', links_path %></li>
    <li style="float:right"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>

    <!-- <li style="float:right"><p>Logged in as <strong><%= current_user.email %></strong>.</p></li> -->
  <% else %>
    <li style="float:right"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
  <% end %>
</ul>


<!--
<% if user_signed_in? %>
  <ul class="ul1">
    <li><%=link_to "Home", root_path, :class=>"active" %></li>
    <li><%=link_to "Eventos", events_path %></li>
    <li><%=link_to "Noticias", articles_path %></li>
    <li><%=link_to'Contactos', contacts_path %></li>
  </ul>
<% end %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppDipre</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>


    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <!-- <div style="margin-left:25%;padding:1px 16px;height:1000px;"> -->
    <div style="margin: 5%"">
      <%= yield %>
    </div>

  </body>
</html>